# This file was generated by GoReleaser. DO NOT EDIT.
cask "oq" do
  name "oq"
  desc "Terminal OpenAPI Spec viewer"
  homepage "https://github.com/plutov/oq"
  version "0.0.21"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oq"

  on_macos do
    on_intel do
      url "https://github.com/plutov/oq/releases/download/v#{version}/oq_#{version}_darwin_amd64.tar.gz"
      sha256 "d7928d489c25df9ed44c4c09c0dfbdc247b179e27655a3ed2ecc206147276b9d"
    end
    on_arm do
      url "https://github.com/plutov/oq/releases/download/v#{version}/oq_#{version}_darwin_arm64.tar.gz"
      sha256 "c8c1e01bc5c10d1790a4597570e5ce39bd9532d29f9fce6f3b6373c5c0a813af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/plutov/oq/releases/download/v#{version}/oq_#{version}_linux_amd64.tar.gz"
      sha256 "8f7576f247d300faa1e0a9a53abbee86591c728cad2d4ef9570dcdb0d6a5f703"
    end
    on_arm do
      url "https://github.com/plutov/oq/releases/download/v#{version}/oq_#{version}_linux_arm64.tar.gz"
      sha256 "967f51f1a0aa6d31ec56b62e16423f1f3444988f6fac96ae82d29d2066097443"
    end
  end

  # No zap stanza required
end
