# This file was generated by GoReleaser. DO NOT EDIT.
cask "oq" do
  name "oq"
  desc "Terminal OpenAPI Spec viewer"
  homepage "https://github.com/plutov/oq"
  version "0.0.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oq"

  on_macos do
    on_intel do
      url "https://github.com/plutov/oq/releases/tag/v#{version}"
      sha256 "958428f44c777330e14abced36c9511240c5dfda418e714196da6be7c237ac1a"
    end
    on_arm do
      url "https://github.com/plutov/oq/releases/tag/v#{version}"
      sha256 "1493537d939f58945c7fb52a355eea2f942fcc37dd852cad3a616e060786f914"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/plutov/oq/releases/tag/v#{version}"
      sha256 "0352d7d8735c87e6a7c5ce2790fac8a76d036f641acce2e5bde357bd84426fbc"
    end
    on_arm do
      url "https://github.com/plutov/oq/releases/tag/v#{version}"
      sha256 "94acdb2c490aae643409eeeb507590e79825983a6ec045d4e384d9c11d6e822f"
    end
  end

  # No zap stanza required
end
